### ISSUE TITLE
Error when running npm run build or npm run develop

### ISSUE THREAD

**Issue by sroertgen** [hbz/skohub-vocabs#67]
Hello,

I tried to follow your blog entry (http://blog.lobid.org/2019/09/27/presenting-skohub-vocabs.html#implementation) and documentation along, but when running `npm run build` or `npm run develop` I get the following error:

```
> gatsby-starter-default@0.1.0 develop /skohub/skohub-vocabs
> gatsby develop

success open and validate gatsby-configs - 0.065s
success load plugins - 1.245s
success onPreInit - 0.011s
success initialize cache - 0.097s
success copy gatsby files - 0.149s
success onPreBootstrap - 0.024s

 ERROR

Encountered an error parsing the provided GraphQL type definitions:
Syntax Error: Expected Name, found }

  21 |     inbox: String
  22 |   }
  23 |
  24 |   type LanguageMap {
  25 |
> 26 |   }
     |   ^
  27 |


not finished createSchemaCustomization - 0.065s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-02-07T18_22_43_407Z-debug.log
```

log file: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'develop' ]
2 info using npm@6.13.6
3 info using node@v13.7.0
4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]
5 info lifecycle gatsby-starter-default@0.1.0~predevelop: gatsby-starter-default@0.1.0
6 info lifecycle gatsby-starter-default@0.1.0~develop: gatsby-starter-default@0.1.0
7 verbose lifecycle gatsby-starter-default@0.1.0~develop: unsafe-perm in lifecycle true
8 verbose lifecycle gatsby-starter-default@0.1.0~develop: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/steffenroertgen/gwdg_owncloud/coding/skohub/skohub-vocabs/node_modules/.bin:/usr/local/opt/python/libexec/bin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/steffenroertgen/.npm-global/bin
9 verbose lifecycle gatsby-starter-default@0.1.0~develop: CWD: /Users/steffenroertgen/gwdg_owncloud/coding/skohub/skohub-vocabs
10 silly lifecycle gatsby-starter-default@0.1.0~develop: Args: [ '-c', 'gatsby develop' ]
11 silly lifecycle gatsby-starter-default@0.1.0~develop: Returned: code: 1  signal: null
12 info lifecycle gatsby-starter-default@0.1.0~develop: Failed to exec develop script
13 verbose stack Error: gatsby-starter-default@0.1.0 develop: `gatsby develop`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid gatsby-starter-default@0.1.0
15 verbose cwd /Users/steffenroertgen/gwdg_owncloud/coding/skohub/skohub-vocabs
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "develop"
18 verbose node v13.7.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 1
22 error gatsby-starter-default@0.1.0 develop: `gatsby develop`
22 error Exit status 1
23 error Failed at the gatsby-starter-default@0.1.0 develop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by literarymachine** [comment]
Could it be that `prefLabels` and other literals in the vocab you are trying to build do not have language tags:

```
:concept :prefLabel "some label"@en
```

**Comment by sroertgen** [comment]
I used the sample data as mentioned in the README.
